from __future__ import annotations

from io import BytesIO
from pathlib import PurePosixPath
from urllib.parse import quote
from uuid import UUID
from zipfile import ZIP_DEFLATED, ZipFile

from fastapi import APIRouter
from fastapi.responses import Response
from sqlalchemy import func, select
from sqlalchemy.orm import selectinload

from app.api.dependencies import CurrentUser, SessionDependency
from app.core.exceptions import NotFoundError
from app.models.code_file import CodeFile as CodeFileModel
from app.models.enums import ExecutionLogSource, RunStatus, TaskStatus
from app.models.execution_log import ExecutionLog
from app.models.project import Project
from app.models.review_finding import ReviewFinding
from app.models.run import Run
from app.schemas.run import ActivityAgentTaskResponse, ActivityRunResponse, RunDetailResponse
from app.services.realtime import realtime_manager

router = APIRouter(tags=["Runs"])


def _safe_zip_path(path: str, fallback: str) -> str:
    candidate = PurePosixPath(path.replace("\\", "/"))
    parts = [part for part in candidate.parts if part not in {"", ".", ".."}]
    safe_path = PurePosixPath(*parts).as_posix() if parts else fallback
    return safe_path.lstrip("/") or fallback


def _zip_response(project_name: str, run: Run) -> Response:
    if not run.code_files:
        raise NotFoundError("No generated code files are available to download yet")
    buffer = BytesIO()
    used_paths: set[str] = set()
    with ZipFile(buffer, "w", ZIP_DEFLATED) as archive:
        archive.writestr(
            "README.md",
            f"# {project_name}\n\nGenerated by Cortex AI from run `{run.id}`.\nStatus: `{run.status.value}`.\n",
        )
        for index, code_file in enumerate(run.code_files, start=1):
            path = _safe_zip_path(code_file.path, f"generated/file_{index}.txt")
            if path in used_paths:
                stem = PurePosixPath(path).stem or "file"
                suffix = PurePosixPath(path).suffix
                parent = PurePosixPath(path).parent.as_posix().strip(".")
                path = f"{parent}/{stem}_{index}{suffix}" if parent else f"{stem}_{index}{suffix}"
            used_paths.add(path)
            archive.writestr(path, code_file.content)
    filename = f"{_safe_zip_path(project_name, 'project').replace('/', '-')}-cortex-workspace-{str(run.id)[:8]}.zip"
    ascii_filename = "".join(char if char.isalnum() or char in {"-", "_", "."} else "-" for char in filename)
    return Response(
        content=buffer.getvalue(),
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename=\"{ascii_filename}\"; filename*=UTF-8''{quote(filename)}"},
    )


def _activity_response(run: Run, code_file_count: int, review_finding_count: int, execution_log_count: int) -> ActivityRunResponse:
    return ActivityRunResponse(
        id=run.id,
        project_id=run.project_id,
        project_name=run.project.name,
        status=run.status,
        revision_count=run.revision_count,
        started_at=run.started_at,
        finished_at=run.finished_at,
        agent_tasks=[ActivityAgentTaskResponse.model_validate(task) for task in run.agent_tasks],
        code_file_count=code_file_count,
        review_finding_count=review_finding_count,
        execution_log_count=execution_log_count,
    )


@router.get("/activity", response_model=list[ActivityRunResponse])
async def list_activity(user: CurrentUser, session: SessionDependency) -> list[ActivityRunResponse]:
    code_count = select(func.count(CodeFileModel.id)).where(CodeFileModel.run_id == Run.id).correlate(Run).scalar_subquery()
    finding_count = select(func.count(ReviewFinding.id)).where(ReviewFinding.run_id == Run.id).correlate(Run).scalar_subquery()
    log_count = select(func.count(ExecutionLog.id)).where(ExecutionLog.run_id == Run.id).correlate(Run).scalar_subquery()
    rows = (
        await session.execute(
            select(Run, code_count, finding_count, log_count)
            .join(Project)
            .options(selectinload(Run.project), selectinload(Run.agent_tasks))
            .where(Project.user_id == user.id)
            .order_by(Run.started_at.desc().nullslast(), Run.id.desc())
            .limit(25)
        )
    ).all()
    return [_activity_response(run, code_files, findings, logs) for run, code_files, findings, logs in rows]


@router.get("/projects/{project_id}/runs", response_model=list[RunDetailResponse])
async def list_project_runs(project_id: UUID, user: CurrentUser, session: SessionDependency) -> list[Run]:
    runs = list(
        await session.scalars(
            select(Run)
            .join(Project)
            .options(
                selectinload(Run.agent_tasks),
                selectinload(Run.code_files),
                selectinload(Run.review_findings),
                selectinload(Run.execution_logs),
            )
            .where(Project.id == project_id, Project.user_id == user.id)
            .order_by(Run.started_at.desc().nullslast(), Run.id.desc())
            .limit(1)
        )
    )
    return runs


@router.get("/projects/{project_id}/runs/{run_id}", response_model=RunDetailResponse)
async def get_project_run(project_id: UUID, run_id: UUID, user: CurrentUser, session: SessionDependency) -> Run:
    run = await session.scalar(
        select(Run)
        .join(Project)
        .options(
            selectinload(Run.agent_tasks),
            selectinload(Run.code_files),
            selectinload(Run.review_findings),
            selectinload(Run.execution_logs),
        )
        .where(Run.id == run_id, Run.project_id == project_id, Project.user_id == user.id)
    )
    if run is None:
        raise NotFoundError("Run not found")
    return run


@router.post("/projects/{project_id}/runs/{run_id}/cancel", response_model=RunDetailResponse)
async def cancel_project_run(project_id: UUID, run_id: UUID, user: CurrentUser, session: SessionDependency) -> Run:
    run = await session.scalar(
        select(Run)
        .join(Project)
        .options(
            selectinload(Run.agent_tasks),
            selectinload(Run.code_files),
            selectinload(Run.review_findings),
            selectinload(Run.execution_logs),
        )
        .where(Run.id == run_id, Run.project_id == project_id, Project.user_id == user.id)
    )
    if run is None:
        raise NotFoundError("Run not found")
    if run.status in {RunStatus.pending, RunStatus.running}:
        run.status = RunStatus.cancelled
        for task in run.agent_tasks:
            if task.status in {TaskStatus.pending, TaskStatus.running}:
                task.status = TaskStatus.cancelled
        session.add(ExecutionLog(run_id=run.id, source=ExecutionLogSource.agent_reasoning, content="Run cancelled by user"))
        await session.commit()
        await session.refresh(run)
        payload = {"project_id": str(project_id), "run_id": str(run_id), "status": run.status.value}
        await realtime_manager.broadcast_project(project_id, "run.cancelled", payload)
        await realtime_manager.broadcast_user(user.id, "run.cancelled", payload)
    return run


@router.get("/projects/{project_id}/download")
async def download_latest_project(project_id: UUID, user: CurrentUser, session: SessionDependency) -> Response:
    run = await session.scalar(
        select(Run)
        .join(Project)
        .join(CodeFileModel)
        .options(selectinload(Run.code_files), selectinload(Run.project))
        .where(Project.id == project_id, Project.user_id == user.id)
        .order_by(Run.finished_at.desc().nullslast(), Run.started_at.desc().nullslast(), Run.id.desc())
    )
    if run is None:
        raise NotFoundError("No generated project run found")
    return _zip_response(run.project.name, run)


@router.get("/projects/{project_id}/runs/{run_id}/download")
async def download_project_run(project_id: UUID, run_id: UUID, user: CurrentUser, session: SessionDependency) -> Response:
    run = await session.scalar(
        select(Run)
        .join(Project)
        .options(selectinload(Run.code_files), selectinload(Run.project))
        .where(Run.id == run_id, Run.project_id == project_id, Project.user_id == user.id)
    )
    if run is None:
        raise NotFoundError("Run not found")
    return _zip_response(run.project.name, run)
