[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioboto3>=15.5.0",
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "bandit>=1.9.4",
    "crewai>=1.15.17",
    "fastapi[all]>=0.139.2",
    "greenlet>=3.5.4",
    "psycopg2-binary>=2.9.12",
    "pwdlib[argon2]>=0.3.0",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "pymupdf>=1.28.2",
    "python-docx>=1.2.0",
    "scalar-fastapi==1.8.2",
    "sqlmodel>=0.0.39",
    "supabase>=2.31.0",
    "uvicorn>=0.51.0",
]

[tool.vercel]
entrypoint = "main:app"
